### ISSUE TITLE
I cannot uninstall the theme

### ISSUE THREAD

**Issue by duverj** [raveneyex/raven-theme-01-syntax#4]
When trying to uninstall I got this message: 
Uninstalling “raven-warm-syntax” failed. Hide output…
       Failed to delete raven-warm-syntax: Does not exist

**Comment by raveneyex** [comment]
@duverj Say what?
I was able to uninstall. Let's troubleshoot later on.

**Comment by raveneyex** [comment]
This was a local issue.
